export const QUERY_KEYS = {

    AUTH: {
        USER_INFO: "USER_INFO",
    },
    USER:
    {
        LIST_USER_IN_COMPANY_OWNER: "LIST_USER_IN_COMPANY_OWNER",
        LIST_BOOKING_REQUEST: "LIST_BOOKING_REQUEST",
        LIST_DETAIL_BOOKING_REQUEST: "LIST_DETAIL_BOOKING_REQUEST",
        LIST_AGENT_REQUEST: "LIST_AGENT_REQUEST",
        LIST_REPORT_PAYABLE_BOOKING_ITEM_BY_AGENT: "LIST_REPORT_PAYABLE_BOOKING_ITEM_BY_AGENT",
        LIST_REPORT_COMMISSION_BY_AGENT_HOST: "LIST_REPORT_COMMISSION_BY_AGENT_HOST",
        LIST_PAID_BOOKING_ITEM: "LIST_PAID_BOOKING_ITEM",
        LIST_COMPANY_OWNER: "LIST_COMPANY_OWNER",
        LIST_TOUR_CUSTOMIZED: "LIST_TOUR_CUSTOMIZED",
        LIST_COMPANY_BANK_ACCOUNT: "LIST_COMPANY_BANK_ACCOUNT",
        LIST_SALE_REQUEST: "LIST_SALE_REQUEST",
        LIST_AGENT_FOR_GROUP: "LIST_AGENT_FOR_GROUP",
        LIST_REPORT_RECEIV_ABLE_BY_AGENT: "LIST_REPORT_RECEIV_ABLE_BY_AGENT",
        LIST_AGENT_HOST_SERVICE_ITEM: "LIST_AGENT_HOST_SERVICE_ITEM",
        LIST_PAYABLE_BOOKING: "LIST_PAYABLE_BOOKING",
        LIST_PAID_BOOKING: "LIST_PAID_BOOKING",
        LIST_REQUEST_MESSAGE: "LIST_REQUEST_MESSAGE",
        LIST_SERVICE_ITEM_BY_SALE_REQ: "LIST_SERVICE_ITEM_BY_SALE_REQ",
        LIST_BOOKING: "LIST_BOOKING",
        LIST_HELPER_FILE_BY_SHOW: "LIST_HELPER_FILE_BY_SHOW",
        LIST_AGENT_NOTIFY: "LIST_AGENT_NOTIFY",
    }

};
